[package]
name = "elbrus-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
elbrus-core = { path = "../elbrus-core" }
uuid.workspace = true
serde.workspace = true
thiserror.workspace = true
